spring:
  application:
    name: chaekmate-front

chaekmate:
  gateway:
    url: http://localhost:8080

server:
  port: 5173
  forward-headers-strategy: native

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}
  chaekmateImageUrl: ${CHAEKMATE_IMAGE_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  instanceId: ${spring.application.name}:${server.port}
